Repository bats-core/bats-core, pull requests merged in 2018-06, with the labels that each got.

#35 Add a Gitter chat badge to README.md
  README.md
Labels: review

#63 Adds table of contents to the README
  README.md
Labels: review

#87 Emit correct trace after calling exported function
  .travis.yml
  Dockerfile
  libexec/bats-exec-test
  test/bats.bats
  test/fixtures/bats/exported_function.bats
Labels: review

#88 Cleanup
  .appveyor.yml
  README.md
  bin/bats
  install.sh
  libexec/bats
  libexec/bats-exec-suite
  libexec/bats-exec-test
  libexec/bats-format-tap-stream
  libexec/bats-preprocess
  test/bats.bats
  test/fixtures/bats/failing_teardown.bats
  test/fixtures/bats/setup.bats
  test/fixtures/bats/teardown.bats
  test/test_helper.bash
  test/tmp/.gitignore
Labels: review

#91 bin/bats, install.sh: Fix symlink bugs
  Dockerfile
  bin/bats
  install.sh
  libexec/bats
  libexec/bats-exec-test
  test/install.bats
Labels: bug, review

#66 Adds next version changelog
  README.md
Labels: review

#92 Pre v1.0.0 cleanup
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE.md
  README.md
  bin/bats
  docs/CODEOWNERS
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
  install.sh
  libexec/bats
  libexec/bats-exec-test
  test/bats.bats
  test/fixtures/bats/unofficial_bash_strict_mode.bash
  test/install.bats
Labels: review, target: 1.0

#98 Fix BATS_CWD bug introduced in #91
  libexec/bats
  test/bats.bats
Labels: bug, review

#99 Ensure last line of output prints without newline
  libexec/bats-exec-test
  test/bats.bats
  test/fixtures/bats/no-final-newline.bats
Labels: bug, review

#94 docs: add usage guide
  docs/usage.md
Labels: review

#101 Update readme badges
  README.md
Labels: review

#100 Publish to npm
  AUTHORS
  README.md
  package.json
Labels: review

#104 README: Update installation for macOS, npm
  README.md
Labels: docs, review
