Repository bats-core/bats-core, pull requests merged in 2018-07, with the labels that each got.

#114 docs: correct docker organisation name
  README.md
Labels: review

#117 travis: Enable build with default Linux image Bash
  .travis.yml
Labels: review

#118 Add error message for bad command line options
  libexec/bats-core/bats
  libexec/bats-core/bats-exec-test
  test/bats.bats
Labels: review

#115 Fix BATS_ROOT resolution when /bin => /usr/bin
  bin/bats
  test/install.bats
  test/root.bats
  test/test_helper.bash
Labels: bug, review

#120 bats: Replace echo with printf
  docs/CONTRIBUTING.md
  libexec/bats-core/bats
  libexec/bats-core/bats-exec-suite
  libexec/bats-core/bats-exec-test
  libexec/bats-core/bats-format-tap-stream
  libexec/bats-core/bats-preprocess
Labels: review

#123 Makes appveyor version semver compliant
  .appveyor.yml
Labels: review

#122 Create docs/CHANGELOG.md, docs/releasing.md
  README.md
  docs/CHANGELOG.md
  docs/releasing.md
Labels: docs, review
